# Generated by Django 4.2.9 on 2024-12-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_task_category_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
